[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ncwm"
version = "0.1.0"
description = "Neural Cellular Automata World Model Library"
authors = [
    { name = "Veddy1674" }
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["ncwm*"]